### ISSUE TITLE
Is it covered with PHP version 7.3 and more?

### ISSUE THREAD

**Issue by ghost** [bhashkar007/first-image#1]
When I use first-image with PHP 7.3, I got the error message as below.

preg_match(): Compilation failed: invalid range in character class at offset 4.

**Comment by hasmitapatel** [comment]
> When I use first-image with PHP 7.3, I got the error message as below.
> 
> preg_match(): Compilation failed: invalid range in character class at offset 4.

I had the same problem but I fixed it from seeing this on a Stack Overflow post https://stackoverflow.com/questions/24764212/preg-match-compilation-failed-invalid-range-in-character-class-at-offset 

But this is the gist of it:

PCRE2 is more strict in the pattern validations, so after the upgrade, some of your existing patterns could not compile anymore.

preg_match('/[\w-.]+/', ''); // this will not work in PHP7.3
**preg_match('/[\w\-.]+/', ''); // the hyphen need to be escaped**

As you can see from the example above there is a little but substantial difference between the two lines.

You just need to go into vendor/by/first-image/src/libs/simplehtmldom_1_5/simple_html_dom.php and add a \ between w and any hyphen you see
